### ISSUE TITLE
Easier way to run multiple transforms against a project?

### ISSUE THREAD

**Issue by pdehaan** [cpojer/js-codemod#48]
I love this project, but I think I'm not fully understanding how to run transforms against my projects.

The README shows the easiest way of setting up your repo using something like:

```sh
$ npm install -g jscodeshift
$ npm install cpojer/js-codemod -D
$ jscodeshift -t <transform> <file>
```

But then it seems like I need to run each transform individually against a set of files.
Is there a way you can run multiple transforms at once without needing to re-run those commands every time I make some changes or add new files?

I was hoping there would be some Gulp plugin or even something like a .jscodeshiftrc file which lets you specify something like:

```yaml
transforms:
  js-codemod/transforms/arrow-function-arguments: 1
  js-codemod/transforms/arrow-function: [1, {inline-single-expressions: true}]
  js-codemod/transforms/invalid-requires: 1
  ...
```

(sort of like how .eslintrc works, where "js-codemod" would be resolved againt files in ./node_modules/js-codemod/*)

And then be able to run `$ jscodeshift *.js` in a project and have it run each transform in my config file against the specified glob of files.
